Machine Learning - Quiz 3
========================================================

Question 1
----------
```{r}
library(AppliedPredictiveModeling)
data(segmentationOriginal)
library(caret)

train <- segmentationOriginal[segmentationOriginal$Case == "Train",]
test <- segmentationOriginal[segmentationOriginal$Case == "Test",]

set.seed(125)
fit <- train(Class~.,method="rpart",data=train)

print(fit)
plot(fit$finalModel,uniform=TRUE)
text(fit$finalModel, use.n=TRUE, all=TRUE, cex=.8)

data.a <- data.frame(TotalIntench2 = 23,000, FiberWidthCh1 = 10, PerimStatusCh1=20)
data.b <- data.frame( TotalIntench2 = 50,000, FiberWidthCh1 = 10,VarIntenCh4 = 100)
data.c <- data.frame(TotalIntench2 = 57,000, FiberWidthCh1 = 8,VarIntenCh4 = 100)
data.d <- data.frame(FiberWidthCh1 = 8,VarIntenCh4 = 100, PerimStatusCh1=2) 

predict(fit,data.a)

```

Question 3
----------
```{r}
library(pgmm)
data(olive)
olive = olive[,-1]

library(tree)
fit.q3 <- tree(Area~.,olive)
print(fit.q3)

newdata = as.data.frame(t(colMeans(olive)))

predict(fit.q3,newdata)
```


Question 4
----------
```{r}
library(ElemStatLearn)
data(SAheart)
set.seed(8484)
train = sample(1:dim(SAheart)[1],size=dim(SAheart)[1]/2,replace=F)
trainSA = SAheart[train,]
testSA = SAheart[-train,]

fit.q4 <- train(chd ~ age + alcohol + obesity + tobacco + typea + ldl,
                data=trainSA,
                method="glm",
                family="binomial")

print(fit.q4)


missClass = function(values,prediction){sum(((prediction > 0.5)*1) != values)/length(values)}

missClass(testSA$chd,predict(fit.q4,testSA))

missClass(trainSA$chd,predict(fit.q4,trainSA))



```


Question 5
----------
```{r}
library(ElemStatLearn)
data(vowel.train)
data(vowel.test) 
library(plyr)

vowel.train <- mutate(vowel.train,y=factor(y))
vowel.test <- mutate(vowel.test,y=factor(y))

library(randomForest)
set.seed(33833)
# fit.q5 <- train(y~.,method="rf",data=vowel.train)
fit.q5 <- randomForest(y~.,data=vowel.train)

print(fit.q5)

rownames(varImp(fit.q5))[rev(order(varImp(fit.q5)$Overall))]


```

